# Generated by Django 6.0 on 2025-12-22 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('movie', 'Pelicula'), ('series', 'Serie')], max_length=10)),
                ('genres', models.ManyToManyField(to='api.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=150)),
                ('duration_minutes', models.IntegerField()),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='api.base')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('season_count', models.IntegerField()),
                ('episodes_count', models.IntegerField()),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='api.base')),
            ],
        ),
    ]
